# Use the official MySQL image as the base
FROM mysql:latest

# Set environment variables
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

# Change ownership of MySQL data directory
RUN chown -R mysql:root /var/lib/mysql/

# Expose port 3306
EXPOSE 3306